services:
  api:
    build:
      context: ..
      dockerfile: configs/Dockerfile.api
    env_file:
      - ../.env
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ..
      dockerfile: configs/Dockerfile.frontend
    ports:
      - "4173:4173"
    depends_on:
      - api
